let hambre = prompt ("¿Tenes hambre?")
if (hambre == "si")
alert("Te ganaste un Big Mac")
else if (hambre =="no")
alert("Acabas de perder la mejor hamburgesa de tu vida")
else if (hambre == "nose")
alert("Pensa bien tu respuesta...")